### PR TITLE
Last synchronization date display on metabox

### PR DESCRIPTION
**Pull request by jnmrclmbsjse**
This PR includes:
1. Show formatted date on sync metabox instead of raw UTC date.

Webshop in amsterdam timezone:
image

Backoffice in same timezone:
image

### CODE REVIEW

**Comment by jnmrclmbsjse** [comment]
Task linked: [CU-865d4zjmp Last synchronization date wrong value](https://app.clickup.com/t/865d4zjmp)

**Comment by ikulis** [comment]
@jnmrclmbsjse Why do we show both dates in UTC instead of correct timezone? Also how you show it it's really not clear the date is in UTC

**Review by ikulis — COMMENTED** [review]
changes looks good, but maybe something is missing when sending to backend or showing in backoffice

**Comment by jnmrclmbsjse** [comment]
> @jnmrclmbsjse Why do we show both dates in UTC instead of correct timezone? Also how you show it it's really not clear the date is in UTC

In webshop we have decided to keep all dates in UTC when saved to DB and just format it to whichever the wordpress timezone is selected. For backoffice I'm not sure if it's supported to send a date with timezone.

**Comment by ikulis** [comment]
> In webshop we have decided to keep all dates in UTC when saved to DB 
They should be saved in UTC, but shown to user base on the woocomerce setting

>  For backoffice I'm not sure if it's supported to send a date with timezone.
You can send it in ISO 8601 date 'c' format `2004-02-12T15:19:21+00:00`  see https://www.php.net/manual/en/datetime.format.php

**Comment by ikulis** [comment]
> Would you agree if we do this in a separate task instead of this PR?

No, because all date/times in backoffice are in user timezone, so showing only this one in UTC is incorrect.

**Comment by jnmrclmbsjse** [comment]
> No, because all date/times in backoffice are in user timezone, so showing only this one in UTC is incorrect.
Fixed

Webshop in amsterdam timezone:
image

Backoffice in same timezone:
image

**Pull request merged**
